### ISSUE TITLE
Add IBM Z and LinuxOne assets

### ISSUE THREAD

**Issue by v1gnesh** [IBM/ibmdiagrams#1]
Please add IBM Z and LinuxOne assets.
Surely they already exist and are in use for IBM docs, at least in some products.
Allow your customers to create these for their own envs.

**Comment by jaywarfield** [comment]
Agreed and we have started including Z icons but need to make sure the icons are exposed here and maybe include a diagram as code example in the readme.  Thanks!

**Comment by jaywarfield** [comment]
Agreed and we have started including an initial set of Z icons!  An incorrect component color was used on some so that has been fixed and will be included in the next release. Thanks for choosing IBM Cloud!
